const data = {
  users: [
    {
      name: "Thuy",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Squirrel Squishy",
      slug: "1-squishy",
      category: "Squishy",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
    {
      //_id: "2",
      name: "Icecream Squishy",
      slug: "2-squishy",
      category: "Squishy",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
    {
      //_id: "3",
      name: "Dino Squishy",
      slug: "3-squishy",
      category: "Squishy",
      image: "/images/p3.jpg",
      price: 110,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
    {
      //_id: "4",
      name: "Nemo Squishy",
      slug: "4-squishy",
      category: "Squishy",
      image: "/images/p4.jpg",
      price: 115,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
  ],
};
export default data;
