const data = {
  products: [
    {
      name: "Squirrel Squishy",
      slug: "1-squishy",
      category: "Squishy",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
    {
      name: "Icecream Squishy",
      slug: "2-squishy",
      category: "Squishy",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
    {
      name: "Dino Squishy",
      slug: "3-squishy",
      category: "Squishy",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
    {
      name: "Nemo Squishy",
      slug: "4-squishy",
      category: "Squishy",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Squishy",
      rating: 4.5,
      numReviews: 10,
      description: "high quality squishy",
    },
  ],
};
export default data;
